require("user.launch")
require("user.options")
require("user.keymaps")

spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.none_ls")
spec("user.nvim_tree")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.cmp")
spec("user.autopairs")
spec("user.whichkey")
spec("user.telescope")
spec("user.comment")
spec("user.lualine")

require("user.lazy")
