require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")

spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.none_ls")
-- spec("user.nvim_tree")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.cmp")
spec("user.autopairs")
spec("user.whichkey")
spec("user.telescope")
spec("user.comment")
spec("user.lualine")
spec("user.dropbar")
spec("user.harpoon")
spec("user.neoscroll")
spec("user.illuminate") -- Highlight word under cursor in file
spec("user.oil")
spec("user.ufo") -- Folding
spec("user.neotest")
spec("user.modicator") -- Match line number color with lualine status color
spec("user.tabout")
spec("user.gitsigns")
spec("user.lazygit")
spec("user.dashboard")
spec("user.toggleterm")
-- spec("user.tabby")
-- spec("user.indentline")
-- spec("user.navbuddy")
-- spec("user.trouble")

require("user.lazy")
